# Generated by Django 2.1.5 on 2019-05-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conact',
            new_name='Contact',
        ),
    ]
